### ISSUE TITLE
首页一直加载，没有数据

### ISSUE THREAD

**Issue by lovefox666** [CuteFakin/Fakin-Reader#1]
怎么回事？

**Comment by ZpsssLll** [comment]
具体是什么样的

**Comment by ZpsssLll** [comment]
控制台有输出报错吗？

**Comment by lovefox666** [comment]
先git大佬的api接口

git https://github.com/xiadd/zhuishushenqi.git
npm instal
npm run dev

我是直接clone你的项目，直接npm install。没有进行你的这步大佬的接口，有问题么？该如何正确操作？

**Comment by ZpsssLll** [comment]
直接clone我的项目不行的，因为我是项目中都是用大佬api的，你的先clone大佬的项目，然后在本地跑起来大佬的项目，在启动本项目即可~
