### ISSUE TITLE
请问一下您写的axios的配置有什么用？

### ISSUE THREAD

**Issue by AkihaIzayoi** [CuteFakin/Fakin-Reader#4]
src/api/axios
src/api/index
这里的东西都没有看到在其他文件里被使用或者引入过？
请问这里写的axios配置应该如何调用或者使用和引入

**Comment by AkihaIzayoi** [comment]
> src/api/axios
> src/api/index
> 这里的东西都没有看到在其他文件里被使用或者引入过？
> 请问这里写的axios配置应该如何调用或者使用和引入

**Comment by CuteFakin** [comment]
上个版本的忘记删除了，没有任何实质用于~
